baseURL = "https://seattlectf.com/"
languageCode = "en-us"
title = "SeattleCTF"
theme = "typer"

#JS plugins
#place jquery first always
[[params.plugins.js]]
URL = "js/cookies.js"
[[params.plugins.js]]
URL = "js/analytics.js"
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/typer.js"

#CSS
[[params.plugins.css]]
URL = "css/typer.css"
[[params.plugins.css]]
URL = "css/fa.css"
[[params.plugins.css]]
URL = "css/social.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.css]]
URL = "css/cookies.css"

[[params.plugins.favicon]]
URL = "images/favicon.png"
[[params.plugins.logo]]
URL = "images/logo.png"

[params]
lang = "en"
typerfile = "js/typer.txt"
title = "SeattleCTF | Become L33t"
shortTitle = "Become L33t"
description = "A group dedicated to becoming the best penetration testers. We play Capture the Flags (CTFs) to hone our skills as computer security experts. Join us in our meetings and become a l33t hacker."

[[params.twittercard]]
  type = "summary"
  site = "@SeattleCTF"
  creator = "@SeattleCTF"
  title = "Become l33t through CTFs"
  description = "A group dedicated to becoming the best penetration testers. We play Capture the Flags (CTFs) to hone our skills as computer security experts. Join us in our meetings and become a l33t hacker."
  imagesrc = "https://seattlectf.com/images/favicon.png"
  url = "https://seattlectf.com"

[[params.opengraph]]
  title = "SeattleCTF | Become L33t"
  image = "images/logo.png"
  url = "https://seattlectf.com"
  site_name = "SeattleCTF Flag Grabbers"
  type = "blog"

[[params.social]]
  name = "Slack"
  icon = "fab fa-slack"
  weight = "1"
  url = "https://joinslack.seattlectf.com"
[[params.social]]
  name = "Meetup"
  icon = "fab fa-meetup"
  weight = "2"
  url = "https://www.meetup.com/seattlectf/"
[[params.social]]
  name = "Git"
  icon = "fab fa-git"
  weight = "3"
  url = "https://git.seattlectf.com"
[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter"
  weight = "4"
  url = "https://twitter.com/seattlectf"
